# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        none

# Setup
title:            Státnice
tagline:          'Poznámky k Mgr. státnicím na MFF, I3 obecná lingvistika'
description:      'Moje poznámky k mým MFF státnicím. Autor <a href="http://karelbilek.com">Karel Bílek</a>; používá Jekyll a téma <a href="http://lanyon.getpoole.com">lanyon</a>.'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Karel Bílek'
  url:            http://karelbilek.com

# Custom vars
version:          1.0.11

github:
  repo:           https://github.com/poznamkymgrstatnice/poznamkymgrstatnice.github.io
